import com.vanniktech.maven.publish.JavaLibrary
import com.vanniktech.maven.publish.JavadocJar

plugins {
    id 'java'
    id 'maven-publish'
    id 'signing'
    id 'com.vanniktech.maven.publish' version '0.37.0'
}

group = 'com.kyfstore'
version = '1.0.1'

repositories {
    mavenCentral()
}

dependencies {
    // SQL Drivers
    implementation 'org.xerial:sqlite-jdbc:3.49.1.0'
    implementation 'org.postgresql:postgresql:42.7.5'

    // Formats (JSON, XML, YAML, TOML)
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.18.2'
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.18.2'
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.18.2'
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-toml:2.18.2'

    // HOCON / CONF
    implementation 'com.typesafe:config:1.4.3'

    // LZMA Compression
    implementation 'org.tukaani:xz:1.10'

    testImplementation platform("org.junit:junit-bom:${project.junit_version}")
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

java {
    withSourcesJar()
}

mavenPublishing {
    coordinates(group.toString(), 'tinystore', version.toString())

    configure(new JavaLibrary(
            new JavadocJar.Javadoc(),
            true
    ))

    pom {
        name = 'TinyStore'
        description = 'TinyStore is a format-agnostic, zero-friction storage layer for Java. Store structured objects into SQLite, PostgreSQL, or flat files using JSON, YAML, TOML, or binary payloads - with built-in compression pipelines and automatic TTL expiration out of the box.'
        inceptionYear = '2026'
        url = 'https://github.com/lammy12k/TinySTore'

        licenses {
            license {
                name = 'MIT License'
                url = 'https://opensource.org'
            }
        }
        developers {
            developer {
                id = 'lammy12k'
                name = 'lammy12k'
                email = ''
            }
        }
        scm {
            connection = 'scm:git:git://://github.com'
            developerConnection = 'scm:git:ssh://://github.com'
            url = 'https://github.com/lammy12k/TinyStore'
        }
    }

    publishToMavenCentral()
    signAllPublications()
}